// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// get credentials from the env
const apiUrl = import.meta.env.VITE_SUPABASE_URL;
const apiKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if(!apiKey || !apiUrl){
  throw 'CREDENTIALS NOT SET';
}


export const supabase = createClient<Database>(apiUrl, apiKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});